version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - MICROBLOG_DB__uri=mongodb://mongodb:27017/microblog
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - mongodb_data:/data/db

volumes:
  mongodb_data:

