"""like_relationship

Revision ID: efa6bad990cc
Revises: cca07cc114fd
Create Date: 2025-05-30 18:15:17.980705

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'efa6bad990cc'
down_revision = 'cca07cc114fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'post',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'post',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
