"""fix_social_relationships

Revision ID: f0a8ea73db88
Revises: acfd91ff41c1
Create Date: 2025-05-30 00:12:42.380158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f0a8ea73db88'
down_revision = 'acfd91ff41c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
